ALTER FUNCTION app_auto_consume_calendar_sessions(UUID, TIMESTAMPTZ, TIMESTAMPTZ, DATE, TEXT, TIMESTAMPTZ, UUID)
  SECURITY DEFINER
  SET search_path = public;

REVOKE ALL ON FUNCTION app_auto_consume_calendar_sessions(UUID, TIMESTAMPTZ, TIMESTAMPTZ, DATE, TEXT, TIMESTAMPTZ, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_auto_consume_calendar_sessions(UUID, TIMESTAMPTZ, TIMESTAMPTZ, DATE, TEXT, TIMESTAMPTZ, UUID) FROM anon;
GRANT EXECUTE ON FUNCTION app_auto_consume_calendar_sessions(UUID, TIMESTAMPTZ, TIMESTAMPTZ, DATE, TEXT, TIMESTAMPTZ, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION app_auto_consume_calendar_sessions(UUID, TIMESTAMPTZ, TIMESTAMPTZ, DATE, TEXT, TIMESTAMPTZ, UUID) TO project_admin;
